{{- if .Values.debug.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cca-frontend.componentName" (dict "root" . "component" "debug") }}
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: debug
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "appl.selectorLabels" . | nindent 6 }}
      component: debug
  template:
    metadata:
      labels:
        {{- include "appl.selectorLabels" . | nindent 8 }}
        component: debug
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "appl.serviceAccountName" . }}
      containers:
        - name: debug
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - cat
          env:
            - name: PORT
              value: "3000"
            - name: RAZZLE_SENTRY_RELEASE
              value: "{{ include "cca-frontend.releaseVersion" . }}"
            - name: RAZZLE_FRONTEND_VERSION
              value: "{{ .Values.volto.environment.RAZZLE_FRONTEND_VERSION | default (include "cca-frontend.releaseVersion" .) }}"
            - name: RAZZLE_FRONTEND_NAME
              value: "{{ .Values.volto.environment.RAZZLE_FRONTEND_NAME | default .Chart.Name }}"
            - name: RAZZLE_PUBLIC_URL
              value: "{{ include "cca-frontend.publicURL" . }}"
            - name: SENTRY_RELEASE
              value: "{{ include "cca-frontend.releaseVersion" . }}"
            - name: TZ
              value: "{{ .Values.timezone }}"
            - name: VOLTO_ROBOTSTXT
              value: |-
{{ include "cca-frontend.robotsTxt" . | nindent 16 }}
            {{- range $key, $value := .Values.volto.environment }}
            {{- if and $value (ne $key "RAZZLE_FRONTEND_VERSION") (ne $key "RAZZLE_FRONTEND_NAME") (ne $key "RAZZLE_PUBLIC_URL") (ne $key "VOLTO_ROBOTSTXT") }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          ports:
            - containerPort: 3000
              name: http
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: {{ .Values.debug.addonsPath }}
              name: debug-addons
          resources:
            {{- toYaml .Values.debug.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.debug.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.debug.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.debug.tolerations | nindent 8 }}
      volumes:
        - name: debug-addons
          persistentVolumeClaim:
            claimName: debug-addons-pvc
{{- end }}
