{{- if and .Values.nginx.basicAuth.username .Values.nginx.basicAuth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cca-frontend.componentName" (dict "root" . "component" "nginx-basic-auth") }}
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: nginx
type: Opaque
data:
  .htpasswd: {{ htpasswd .Values.nginx.basicAuth.username .Values.nginx.basicAuth.password | b64enc }}
{{- end }}
