apiVersion: apps/v1
kind: Deployment
metadata:
  name: volto
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: volto
spec:
  replicas: {{ .Values.volto.replicaCount }}
  selector:
    matchLabels:
      {{- include "appl.selectorLabels" . | nindent 6 }}
      component: volto
  template:
    metadata:
      labels:
        {{- include "appl.selectorLabels" . | nindent 8 }}
        component: volto
      {{- with .Values.volto.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "appl.serviceAccountName" . }}
      containers:
        - name: volto
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: "3000"
            - name: RAZZLE_SENTRY_RELEASE
              value: "{{ include "cca-frontend.releaseVersion" . }}"
            - name: RAZZLE_FRONTEND_VERSION
              value: "{{ .Values.volto.environment.RAZZLE_FRONTEND_VERSION | default (include "cca-frontend.releaseVersion" .) }}"
            - name: RAZZLE_FRONTEND_NAME
              value: "{{ .Values.volto.environment.RAZZLE_FRONTEND_NAME | default .Chart.Name }}"
            - name: SENTRY_RELEASE
              value: "{{ include "cca-frontend.releaseVersion" . }}"
            - name: TZ
              value: "{{ .Values.timezone }}"
            {{- range $key, $value := .Values.volto.environment }}
            {{- if and $value (ne $key "RAZZLE_FRONTEND_VERSION") (ne $key "RAZZLE_FRONTEND_NAME") }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          ports:
            - containerPort: 3000
              name: http
          {{- if .Values.volto.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.volto.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.volto.startupProbe }}
          startupProbe:
            {{- toYaml .Values.volto.startupProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.volto.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.volto.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.volto.resources | nindent 12 }}
      {{- with .Values.volto.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volto.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volto.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
