apiVersion: v2
name: logcentral-graylog5
description: Graylog 6.0 centralized logging solution with MongoDB, Postfix, and load balancer
icon: https://global-uploads.webflow.com/5a218ef7897bf400019e2f16/5a218ef7897bf400019e2f60_logo-graylog.png

type: application

keywords:
  - graylog
  - logs
  - syslog
  - gelf
  - mongodb
  - postfix
  - logcentral

version: 1.0.1

appVersion: "6.0"

dependencies: []
