# Default values
clusterRole:
  name: "pod-reader"
  description: "To introspect Rancher2 resources and generate Redmine/Taskman wiki pages"
  rules:
    - apiGroups: [""]
      resources: ["nodes", "pods", "secrets", "namespaces"]
      verbs: ["list"]
clusterRoleBinding:
  name: "read-pods-global"
  creator: "username"
  serviceAccount:
    name: "taskman-wikiman"
    namespace: "wikiman"
