{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-vault.postgres.fullname" . }}
  labels:
    {{- include "agent-vault.labels" . | nindent 4 }}
    component: postgres
spec:
  clusterIP: None
  selector:
    {{- include "agent-vault.postgres.selectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
{{- end }}
