apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-vault.vault.fullname" . }}
  labels:
    {{- include "agent-vault.labels" . | nindent 4 }}
    component: vault
spec:
  type: ClusterIP
  selector:
    {{- include "agent-vault.vault.selectorLabels" . | nindent 4 }}
  ports:
    - name: ui
      port: {{ .Values.agentVault.uiPort }}
      targetPort: ui
      protocol: TCP
    - name: mitm
      port: {{ .Values.agentVault.mitmPort }}
      targetPort: mitm
      protocol: TCP
