apiVersion: v2
name: freshwater-frontend
type: application
version: 2.9.0
appVersion: "2.31.0-demo.02"
description: Wise freshwater frontend
icon: https://raw.githubusercontent.com/eea/helm-charts/main/sources/freshwater-frontend/volto.png
home: https://github.com/eea/freshwater-frontend
keywords:
  - CMS
