apiVersion: v2
name: copernicus-qc-tool
description: Helm chart for the Copernicus QC Tool stack
type: application
version: 0.1.12
appVersion: "2.4.0"
home: https://github.com/eea/helm-charts
keywords:
  - copernicus
  - qc-tool
  - nextcloud
  - postgres
  - mariadb
dependencies:
  - name: postfix
    version: 3.2.0
    repository: https://eea.github.io/helm-charts
