apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "appl.fullname" . }}-config
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    app.kubernetes.io/component: security
data:
  clamd.conf: |
    LogTime yes
    LogClean no
    LogVerbose no
    LogSyslog no
    LogFileMaxSize 0
    PidFile /tmp/clamd.pid
    LocalSocket /tmp/clamd.sock
    TCPSocket 3310
    TCPAddr 0.0.0.0
    DatabaseDirectory /var/lib/clamav
    TemporaryDirectory /tmp
    MaxConnectionQueueLength 200
    MaxThreads 12
    ReadTimeout 300
    ExitOnOOM yes
    Foreground yes
    DetectPUA no
    ScanPE yes
    ScanELF yes
    ScanOLE2 yes
    ScanPDF yes
    ScanSWF yes
    ScanHTML yes
    ScanArchive yes
    ArchiveBlockEncrypted no
    MaxScanSize {{ .Values.maxScanSize }}
    MaxFileSize {{ .Values.maxFileSize }}
    MaxRecursion 16
    MaxFiles 10000
    StreamMaxLength {{ .Values.streamMaxLength }}
    {{- with .Values.extraClamdConf }}
    {{- . | nindent 4 }}
    {{- end }}
