{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cca-admin-legacy-redirect
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: cca-admin-legacy-redirect
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      return 301 https://{{ .Values.plone.hostname }}/admin$is_args$args;
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.plone.hostname }}
      http:
        paths:
          - path: /_admin
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.varnish.serviceName }}
                port:
                  number: {{ .Values.varnish.port }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.plone.hostname }}
      {{- if .Values.ingress.certificate }}
      secretName: {{ .Values.ingress.certificate }}
      {{- end }}
  {{- end }}
{{- end }}
