{{- if .Values.haproxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.haproxy.serviceName }}
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: haproxy
spec:
  type: {{ .Values.haproxy.serviceType }}
  ports:
    - name: http
      port: {{ .Values.haproxy.port }}
      targetPort: http
    - name: stats
      port: {{ .Values.haproxy.statsPort }}
      targetPort: stats
  selector:
    {{- include "appl.selectorLabels" . | nindent 4 }}
    component: haproxy
{{- end }}
