{{- if .Values.ploneTranslate.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ploneTranslate.serviceName }}
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: plone-translate
spec:
  type: {{ .Values.ploneTranslate.serviceType }}
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    {{- include "appl.selectorLabels" . | nindent 4 }}
    component: plone-translate
{{- end }}
