{{- if .Values.ploneAdmin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plone-admin
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: plone-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "appl.selectorLabels" . | nindent 6 }}
      component: plone-admin
  template:
    metadata:
      labels:
        {{- include "appl.selectorLabels" . | nindent 8 }}
        component: plone-admin
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "appl.serviceAccountName" . }}
      containers:
        - name: plone-admin
          image: "{{ .Values.ploneAdmin.image.repository }}:{{ .Values.ploneAdmin.image.tag }}"
          imagePullPolicy: {{ .Values.ploneAdmin.image.pullPolicy }}
          env:
{{ include "cca-backend.backendEnv" (dict "root" . "component" .Values.ploneAdmin) | nindent 12 }}
          ports:
            - name: http
              containerPort: 8080
          {{- if .Values.ploneAdmin.command }}
          command:
            {{- toYaml .Values.ploneAdmin.command | nindent 12 }}
          {{- end }}
          {{- if .Values.ploneAdmin.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.ploneAdmin.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.ploneAdmin.startupProbe }}
          startupProbe:
            {{- toYaml .Values.ploneAdmin.startupProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.ploneAdmin.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.ploneAdmin.readinessProbe | nindent 12 }}
          {{- end }}
          {{- $mounts := include "cca-backend.sharedVolumeMounts" . | trim }}
          {{- if $mounts }}
          volumeMounts:
{{ $mounts | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.ploneAdmin.resources | nindent 12 }}
      {{- $volumes := include "cca-backend.sharedVolumes" . | trim }}
      {{- if $volumes }}
      volumes:
{{ $volumes | nindent 8 }}
      {{- end }}
      {{- with .Values.ploneAdmin.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ploneAdmin.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ploneAdmin.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
