apiVersion: v1
kind: ConfigMap
metadata:
  name: apacheconf

data:
  apache.conf: |
    Listen 8443
    TraceEnable off

    <VirtualHost *:8443>
        ServerName eionet.europa.eu
        Redirect permanent "/" "https://www.eionet.europa.eu/"
    </VirtualHost>

    <VirtualHost *:8443>
        ServerAdmin helpdesk@eionet.europa.eu
        ServerName www.eionet.europa.eu
        ServerSignature Off

        Header set Server HTTPS

        RewriteEngine on

        # styles
        #RewriteRule ^/styles/(.*)  http://mediaserver:80/styles/$1 [P,L]
        #RewriteRule /.well-known/void /void.rdf [R,L]

        # gemet
        RewriteRule /gemet/(latest|([\d\.]+)?)/gemet.rdf.gz http://mediaserver:80/gemet/$1/gemet.rdf.gz [P,L]
        RewriteRule /gemet/static/(.*) http://mediaserver:80/gemet/static/$1 [P,L]
        RewriteRule /gemet/exports/(.*) http://mediaserver:80/gemet/exports/$1 [P,L]
        RewriteRule /gemet/gemet.rdf.gz http://mediaserver:80/gemet/gemet.rdf.gz [P,L]
        RewriteRule /gemet(.*) http://gemet:8888$1 [P,L]
    </VirtualHost>

