apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "appl.fullname" . }}-nginx-config
  labels:
    {{- include "appl.labels" . | nindent 4 }}
data:
  default.conf: |-
    server {
    listen        80;
    server_name   eionet.europa.eu www.eionet.europa.eu;
    access_log /var/log/nginx/access.log main;
  
    location /styles {
      root /opt/zope/var;
      sendfile on;
      tcp_nopush on;
      gzip on;
      gzip_types text/plain application/x-javascript text/css;
      expires 1d;
    }
    
    location ~ ^/gemet/gemet.rdf.gz {
      alias /var/local/gemet/exports/latest/gemet.rdf.gz;
      sendfile on;
      tcp_nopush on;
      expires 1d;
    }
    
    location ~ ^/gemet/(latest|([\d\.]+)?)/gemet.rdf.gz {
      alias /var/local/gemet/exports/$1/gemet.rdf.gz;
      sendfile on;
      tcp_nopush on;
      expires 1d;
    }
    
    location /gemet/exports {
      root /var/local;
      sendfile on;
      tcp_nopush on;
      gzip on;
      gzip_types text/plain application/x-javascript text/css application/rdf+xml;
      expires 1d;
    }
    
    location /gemet/static {
      root /var/local;
      sendfile on;
      tcp_nopush on;
      gzip on;
      gzip_types text/plain application/x-javascript text/css;
      expires 1d;
    }
    }
