apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-client
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: client
spec:
  type: ClusterIP
  selector:
    {{- include "appl.selectorLabels" . | nindent 4 }}
    component: client
  ports:
  - name: http
    port: 9200
    targetPort: 9200
  - name: transport
    port: 9300
    targetPort: 9300
