apiVersion: v2
name: was-scanner
description: Tenable Web App Scanning
type: application
icon: https://raw.githubusercontent.com/eea/helm-charts/main/sources/was-scanner/icon.png

version: 1.0.3

appVersion: "2.109.2-MASTER-I89-D260706-2235"
