{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qctool.secretName" . }}
  labels:
    {{- include "qctool.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.data.postgresPassword | quote }}
  mariadb-password: {{ .Values.secrets.data.mariadbPassword | quote }}
  mariadb-root-password: {{ .Values.secrets.data.mariadbRootPassword | quote }}
  smtp-password: {{ .Values.secrets.data.smtpPassword | quote }}
{{- end }}
