{{- if .Values.mariadb.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "qctool.mariadbName" . }}
  labels:
    {{- include "qctool.labels" . | nindent 4 }}
    component: db
spec:
  serviceName: {{ include "qctool.mariadbServiceName" . }}
  replicas: {{ .Values.mariadb.replicaCount }}
  selector:
    matchLabels:
      {{- include "qctool.selectorLabels" . | nindent 6 }}
      component: db
  template:
    metadata:
      labels:
        {{- include "qctool.selectorLabels" . | nindent 8 }}
        component: db
      {{- with .Values.mariadb.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "qctool.serviceAccountName" . }}
      containers:
        - name: db
          image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}"
          imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
          ports:
            - name: mysql
              containerPort: {{ .Values.mariadb.service.port }}
              protocol: TCP
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.database.name | quote }}
            - name: MYSQL_USER
              value: {{ .Values.mariadb.database.user | quote }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mariadb.database.password | quote }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mariadb.database.rootPassword | quote }}
            {{- range $key := keys .Values.mariadb.extraEnv | sortAlpha }}
            - name: {{ $key }}
              value: {{ index $.Values.mariadb.extraEnv $key | quote }}
            {{- end }}
          args:
            {{- toYaml .Values.mariadb.args | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: mysql
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: mysql
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.mariadb.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "qctool.claimName" (dict "root" . "name" "mariadbData" "volume" .Values.persistence.mariadbData) }}
      {{- with .Values.mariadb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mariadb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mariadb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
