{{- if .Values.loadbalancer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logcentral-graylog5.fullname" . }}-loadbalancer
  labels:
    {{- include "logcentral-graylog5.loadbalancer.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "logcentral-graylog5.loadbalancer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "logcentral-graylog5.loadbalancer.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "logcentral-graylog5.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: loadbalancer
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.loadbalancer.image.repository }}:{{ .Values.loadbalancer.image.tag }}"
          imagePullPolicy: {{ .Values.loadbalancer.image.pullPolicy }}
          env:
            - name: GRAYLOG_HOST
              value: "{{ include "logcentral-graylog5.fullname" . }}-graylog-client"
            - name: LOGSPOUT
              value: "ignore"
            - name: TZ
              value: {{ .Values.global.timezone | quote }}
          ports:
            {{- range .Values.loadbalancer.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol }}
            {{- end }}
          resources:
            {{- toYaml .Values.loadbalancer.resources | nindent 12 }}
      {{- with .Values.loadbalancer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.loadbalancer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.loadbalancer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "logcentral-graylog5.fullname" . }}-loadbalancer
  labels:
    {{- include "logcentral-graylog5.loadbalancer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.loadbalancer.service.type }}
  ports:
    {{- range .Values.loadbalancer.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .containerPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}

  selector:
    {{- include "logcentral-graylog5.loadbalancer.selectorLabels" . | nindent 4 }}
{{- end }}
