image:
  repository: eeacms/eea-query-intent
  pullPolicy: IfNotPresent
  tag: ""

networkSecurity:
  enabled: false

timezone: Europe/Copenhagen

ingress:
  enabled: true
  className: nginx
  annotations: {}
  letsencrypt: "01dev-eea-letsencrypt"
  configuration:
    proxy-body-size: "256m"
    proxy-read-timeout: "180s"
    proxy-send-timeout: "120s"
  tls: true
  certificate: ""
  url: "eea-query-intent.eea.europa.eu"


imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""


livenessProbe:
  httpGet:
    path: /health
    port: 8100
  periodSeconds: 10
  timeoutSeconds: 10
  initialDelaySeconds: 0
  failureThreshold: 5
  successThreshold: 1

startupProbe:
  tcpSocket:
    port: 8100
  failureThreshold: 10
  periodSeconds: 5
  initialDelaySeconds: 5

readinessProbe:
  httpGet:
    path: /health
    port: 8100
  periodSeconds: 10
  timeoutSeconds: 10
  initialDelaySeconds: 0
  failureThreshold: 5
  successThreshold: 1
    

# Enter the names of the Persistent Volume Claims.
# They will be mounted under /mnt
mounts: []

resources:
  limits:
    memory: 2024Mi
  requests:
    memory: 2024Mi



podAnnotations: {}

podSecurityContext: {}

securityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}
