apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-conf

data:
  default.conf: |
    server {
        listen       80;

            location {{ .Values.staticPath }}/ {
            alias /var/local/static/;
            sendfile on;
            tcp_nopush on;
            gzip on;
            gzip_types text/plain application/x-javascript text/css;
            expires 1d;
        }
            location / {
            send_timeout 1800;
            client_body_timeout 400;
            keepalive_timeout 0;
            client_max_body_size 200M;
        }
    }
