# Default values for Sonarqube


securityEnabled: true

image:
  repository: eeacms/esbootstrap
  pullPolicy: Always
  tag: ""

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

url: "esapp.01dev.eea.europa.eu"

timezone: Europe/Copenhagen



esapp:
  replicaCount: 1
  image:
    pullPolicy: Always
  env:
    elastic_host: elastictest01-data-ingress
    AUTO_INDEXING: "false"
    elastic_index: pam
    APP_CONFIG_DIRNAME: ""
    elastic_appalias: "prod"
    elastic_rwuser: "elastic"
    elastic_rwpass: "rwtest"
    elastic_rouser: "elastic"
    elastic_ropass: "rotest"
    SENTRY_DSN: ""
    API_token: ""
    sourceconf_url: ""
    sourceconf_bulksize: ""
    sourceconf_counturl: ""
    DASHBOARD_SRC: ""
  service:
    type: ClusterIP
    port: 3000
  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 512Mi
  livenessProbe:
    httpGet:
      path: /API/v1/healthcheck
      port: 3000
    periodSeconds: 20
    timeoutSeconds: 10
    initialDelaySeconds: 15
    failureThreshold: 3
  startupProbe:
    httpGet:
      path: /API/v1/healthcheck
      port: 3000
    periodSeconds: 5
    timeoutSeconds: 5
    initialDelaySeconds: 15
    failureThreshold: 24

esbootstrap:
  image:
    pullPolicy: Always
  env:
    github_repo: https://github.com/eea/eea.esbootstrap.configs
    DEV_ENV: "false"

ingress:
  enabled: true
  tls: true
  className: "nginx"
  certificate: "esapp.01dev.eea.europa.eu-tls"
  annotations: {}
  letsencrypt: "01dev-eea-letsencrypt"
  configuration:
    proxy-body-size: "256m"
    proxy-read-timeout: "180s"
    proxy-send-timeout: "120s"
  restrictFromInternet: true

storage:
  enabled: true
  configSize: 1Gi
  extensionsSize: 1Gi
  logsSize: 10Gi
  dataSize: 5Gi
  className: "nfs-client"

ide:
  enabled: true
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent
  env:
    TZ: Europe/Copenhagen
    PUID: 0
    PGID: 0
    PASSWORD: password
  resources:
    limits:
      memory: 2Gi
    requests:
      memory: 512Mi
  service:
    type: NodePort

