{{- $labels := ( include "appl.labels" . ) -}}
{{- $values := .Values -}}
{{- $appversion := .Chart.AppVersion }}
{{- $release := .Release.Name }}
{{- range $index, $archiver := .Values.matomocronArchive }}

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $release }}-archive-{{ $index }}
spec:
  schedule: "{{ $archiver.cronSchedule }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ $values.jobs.ttlSecondsAfterFinished }}
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ $release }}-archive
        spec:
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0
          initContainers:
          - name: wait-for-mariadb
            image: busybox
            command: 
              - sh
              - -c
              - >
                until nc -z mariadb 3306;
                do echo waiting for mariadb; sleep 2; done;
          containers:
            - name: matomocron-archive-{{ $index }}
              image: "{{ $values.image.repository }}:{{ $values.image.tag | default $appversion }}"
              imagePullPolicy: "{{ $values.image.pullPolicy }}"
              env:
                - name: MATOMO_DATABASE_HOST
                  value: mariadb
                - name: MATOMO_DATABASE_PORT
                  value: "3306"
                - name: MATOMO_DATABASE_USERNAME
                  value: {{ $values.mariadb.environment.MARIADB_USER | quote }}
                - name: MATOMO_DATABASE_DBNAME
                  value: {{ $values.mariadb.environment.MARIADB_DATABASE | quote }}
                - name: MATOMO_DATABASE_PASSWORD
                  value: {{ $values.mariadb.environment.MARIADB_PASSWORD | quote }}
                - name: ALLOW_EMPTY_PASSWORD
                  value: "no"
                - name: TZ
                  value: "{{ $values.timezone }}"
                - name: MATOMO_URL
                  value: "matomo:{{ $values.matomo.environment.NGINX_HTTP_PORT_NUMBER }}"

                {{- range $key, $value := $archiver.environment }}
                {{- if ($value) }}
                - name: {{ $key }}
                  value: {{ $value | quote }}
                {{- end }}
                {{- end }}

              command:
                - bash
                - -c
              args:
                - /usr/bin/run_archiving.sh
              resources:
                requests:
                  memory: "{{ $archiver.resources.requests.memory }}"
                limits:
                  memory: "{{ $archiver.resources.limits.memory }}"
              volumeMounts:
                - name: matomo-config
                  mountPath: /var/www/html/config
          restartPolicy: Never
          volumes:
                  #            - name: matomo-tmp
                  #              persistentVolumeClaim:
                  #                claimName: {{ $release }}-archive-tmp-pvc
            - name: matomo-config
              persistentVolumeClaim:
                claimName: {{ $release }}-config-pvc

{{- end }}

