---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-matomo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-matomo
      component: matomo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-matomo
        component: matomo
    spec:
      securityContext:
        fsGroup: 82
      initContainers:
        - name: fix-permissions
          image: busybox
          command:
            - sh
            - -c
            - |
              chown -R 82:82 /var/www/html
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: matomo-html
              mountPath: /var/www/html
        - name: wait-for-mariadb
          image: busybox
          command:
            - sh
            - -c
            - >
              until nc -z mariadb 3306;
              do echo waiting for mariadb; sleep 2; done;
      containers:
        - name: matomo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
          env:
            - name: MATOMO_DATABASE_HOST
              value: mariadb
            - name: MATOMO_DATABASE_PORT
              value: "3306"
            - name: MATOMO_DATABASE_ADAPTER
              value: mysql
            - name: MATOMO_DATABASE_TABLES_PREFIX
              value: matomo_
            - name: MATOMO_DATABASE_USERNAME
              value: {{ .Values.mariadb.environment.MARIADB_USER | quote }}
            - name: MATOMO_DATABASE_PASSWORD
              value: {{ .Values.mariadb.environment.MARIADB_PASSWORD | quote }}
            - name: MATOMO_DATABASE_DBNAME
              value: {{ .Values.mariadb.environment.MARIADB_DATABASE | quote }}
            - name: PHP_MEMORY_LIMIT
              value: {{ .Values.matomo.environment.PHP_MEMORY_LIMIT }}
          volumeMounts:
            - name: matomo-html
              mountPath: /var/www/html
            - name: matomo-config
              mountPath: /var/www/html/config
            - name: matomo-plugins
              mountPath: /var/www/html/plugins
            - name: matomo-misc
              mountPath: /var/www/html/misc
          resources:
            requests:
              memory: {{ .Values.matomo.resources.requests.memory }}
            limits:
              memory: {{ .Values.matomo.resources.limits.memory }}
          startupProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 10
            successThreshold: 1
          livenessProbe:
            tcpSocket:
              port: 9000
            periodSeconds: 10
        - name: nginx
          image: nginx:alpine3.23
          ports:
            - containerPort: {{ .Values.matomo.environment.NGINX_HTTP_PORT_NUMBER }}
              name: nginx
          volumeMounts:
            - name: matomo-html
              mountPath: /var/www/html
              readOnly: true
            - name: matomo-plugins
              mountPath: /var/www/html/plugins
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: matomo-misc
              mountPath: /var/www/html/misc
              readOnly: true
          {{- if (.Values.matomo.livenessProbe) }}
          livenessProbe:
            {{- toYaml .Values.matomo.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if (.Values.matomo.startupProbe) }}
          startupProbe:
            {{- toYaml .Values.matomo.startupProbe | nindent 12 }}
          {{- end }}
          {{- if (.Values.matomo.readinessProbe) }}
          readinessProbe:
            {{- toYaml .Values.matomo.readinessProbe | nindent 12 }}
          {{- end }}


      volumes:
        - name: matomo-config
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-config-pvc
        - name: matomo-plugins
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-plugins-pvc
        - name: matomo-misc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-misc-pvc
        - name: nginx-config
          configMap:
            name: {{ .Release.Name }}-nginx-config
        - name: matomo-html
          emptyDir: { }
