apiVersion: v2
name: cdr-py3
description: A CDR Helm chart for Kubernetes (Python 3 / Zope 5+ stack)
icon: https://raw.githubusercontent.com/eea/helm-charts/main/sources/cdr/logo_eionet.png
type: application
version: 0.1.14
appVersion: "z5-1.19"
dependencies:
  - name: rn-zeoserver
    version: 0.2.0
    repository: https://eea.github.io/helm-charts
    alias: zeoserver
  - name: rn-varnish
    version: 0.5.0
    repository: https://eea.github.io/helm-charts
    condition: rn-varnish.enabled
    alias: varnish
  - name: rn-local-converters
    version: 0.1.7
    repository: https://eea.github.io/helm-charts
    condition: rn-local-converters.enabled
    alias: local-converters
  - name: rn-clamav
    version: 1.0.0
    repository: https://eea.github.io/helm-charts
    condition: rn-clamav.enabled
    alias: clamav
