apiVersion: v2
name: alertmanager-gelf-bridge
description: Alertmanager webhook to Graylog GELF HTTP bridge
type: application
version: 0.1.2
appVersion: "0.1.2"
keywords:
  - alertmanager
  - graylog
  - gelf
  - monitoring
home: https://github.com/eea/helm-charts
sources:
  - https://github.com/eea/helm-charts
maintainers:
  - name: EEA
