apiVersion: v1
kind: Service
metadata:
  name: {{ include "appl.fullname" . }}
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    app.kubernetes.io/component: esapp
spec:
  type: {{ .Values.esapp.service.type }}
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "appl.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: esapp
