{{- if .Values.ide.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "appl.fullname" . }}-ide
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    app.kubernetes.io/component: ide
spec:
  type: {{ .Values.ide.service.type }}
  ports:
  - name: http
    targetPort: 8443
  selector:
    {{- include "appl.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ide
{{- end }}
