apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "appl.fullname" . }}-ingress
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: esapp-ingress
  annotations:
  {{- if .Values.ingress.letsencrypt }}
    cert-manager.io/cluster-issuer: "{{ .Values.ingress.letsencrypt }}"
  {{- end }}
  {{- range $key, $value := .Values.ingress.configuration }}
    {{- if ($value) }}
    nginx.ingress.kubernetes.io/{{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if .Values.ingress.restrictFromInternet }}
    nginx.ingress.kubernetes.io/whitelist-source-range: |
      192.168.60.0/22,
      192.168.64.0/21,
      10.92.24.0/21,
      10.50.0.0/16,
      10.20.30.0/24,
      10.0.9.0/24,
      10.50.7.57
  {{- end }}

spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.url }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "appl.fullname" . }}
            port:
              number: 3000
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.url }}
    {{- if .Values.ingress.certificate }}
    secretName: {{ .Values.ingress.certificate }}
    {{- end  }}
  {{- end  }}
