{{- if ( default .Values.securityEnabled true) -}}

{{/*
  By default, allow only access from pods in the same namespace
*/}}


apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-default-security
  labels:
    {{- include "appl.labels" . | nindent 4 }}


spec:
  ingress:
    - from:
        - podSelector: {}
  podSelector: {}
  policyTypes:
    - Ingress

{{- end }}




