apiVersion: v2
name: cca-backend
type: application
version: 0.2.13
appVersion: "v10.0.1-plone6.1"
description: Climate-ADAPT backend
icon: https://raw.githubusercontent.com/eea/helm-charts/main/sources/cca-backend/logo.svg
home: https://climate-adapt.eea.europa.eu
keywords:
  - CMS
dependencies:
  - name: postfix
    version: 3.2.0
    repository: https://eea.github.io/helm-charts
