{{- if .Values.esmaster.clientService.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-client
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: master

spec:
  type: {{ .Values.esmaster.clientService.type }}
  ports:
  - name: "http"
    port: 9200
    targetPort: 9200
  selector:
    {{- include "appl.selectorLabels" . | nindent 4 }}
    component: master
{{- end }}
