apiVersion: v2
name: clms-frontend
type: application
version: 7.41.0
appVersion: "3.562.0"
description: Volto - CLMS frontend
icon: https://raw.githubusercontent.com/eea/helm-charts/main/sources/advisory-board-frontend/volto.png
home: https://github.com/eea/clms-frontend
keywords:
  - React
  - Volto
