apiVersion: v2
name: cca-frontend
type: application
version: 0.1.0
appVersion: "1.113.0"
description: Climate-ADAPT frontend
icon: https://raw.githubusercontent.com/eea/helm-charts/main/sources/cca-frontend/logo.svg
home: https://climate-adapt.eea.europa.eu
keywords:
  - CMS
