image:
  repository: eeacms/cca-frontend
  pullPolicy: Always
  tag: "3.34.0"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

timezone: Europe/Copenhagen
releaseVersion: "1.113.0"

links:
  backend: backend-varnish.cca
  backendTranslate: plone-translate.cca

backend:
  virtualHostRoot: cca

ingress:
  certificate: climate-adapt.eea.europa.eu-tls
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: 01dev-eea-letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "480"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"

ingressredirects: []

volto:
  serviceType: ClusterIP
  hostname: climate-adapt.eea.europa.eu
  publicScheme: https
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 6
    targetMemoryUtilizationPercentage: 60
  replicaCount: 1
  resources:
    limits:
      memory: 2Gi
    requests:
      memory: 2Gi
  environment:
    DANSWER_URL: https://gptlab.eea.europa.eu
    DANSWER_API_KEY: ""
    DEBUG: volto-chatbot
    LLMGW_TOKEN: ""
    LLMGW_URL: https://llmgw.eea.europa.eu
    ONYX_API_KEY: ""
    ONYX_URL: https://aihub.eea.europa.eu/
    RAZZLE_ALLOWED_CORS_DESTINATIONS: ""
    RAZZLE_BACKEND_NAME: cca-backend
    RAZZLE_DEMO_SITE: "false"
    RAZZLE_MATOMO_SITE_ID: "13"
    RAZZLE_MATOMO_URL: https://matomo.eea.europa.eu/
    RAZZLE_PROXY_ES_DSN: ""
    RAZZLE_PROXY_ES_DSN_globalsearch: ""
    RAZZLE_PROXY_ES_DSN_missionAll: ""
    RAZZLE_PROXY_QA_DSN_globalsearch: ""
    RAZZLE_PROXY_QA_DSN_missionAll: ""
    RAZZLE_PUBLIC_URL: ""
    SENTRY_AUTH_TOKEN: ""
    SENTRY_ORG: eea
    SENTRY_PROJECT: climate-adapt-eea-europa.eu
    SENTRY_URL: https://sentry.eea.europa.eu
    VOLTO_ROBOTSTXT: ""
    CSP_HEADER: >-
      default-src 'none'; connect-src 'self' https://*.arcgis.com
      https://services.arcgisonline.com https://*.openstreetmap.org
      https://cds.climate.copernicus.eu https://*.eea.europa.eu
      https://*.eionet.europa.eu; font-src 'self' data: https://js.arcgis.com
      https://cds.climate.copernicus.eu https://cdnjs.cloudflare.com/
      https://*.eea.europa.eu https://*.eionet.europa.eu; frame-src 'self'
      https://mission-climate-adapt-map.agiledrop.com
      https://apps.copernicus-climate.eu https://charts.ecmwf.int
      https://eucra.climate.ifca.es/ https://apps.ecmwf.int https://ec.europa.eu/
      https://geoportal.ecdc.europa.eu https://flo.uri.sh https://*.eea.europa.eu
      https://*.eionet.europa.eu https://eea.maps.arcgis.com; img-src http:
      https: blob: data: https://js.arcgis.com; script-src 'self' {nonce} blob:
      https://matomo.devel4cph.eea.europa.eumatomo.js
      https://fonts.googleapis.com https://matomo.eea.europa.eu
      https://cds.climate.copernicus.eu/ https://openlayers.org/
      https://www.google.com/jsapi https://js.arcgis.com/
      https://public.flourish.studio/ https://*.eea.europa.eu
      https://*.eionet.europa.eu; frame-ancestors 'self'
      https://geoportal.ecdc.europa.eu https://*.eea.europa.eu
      https://*.europa.eu; style-src 'self' 'unsafe-inline'
      https://js.arcgis.com https://openlayers.org/
      https://cds.climate.copernicus.eu/ https://*.eionet.europa.eu
      https://*.eea.europa.eu https://cdnjs.cloudflare.com
      https://charts.ecmwf.int https://eucra.climate.ifca.es/
      https://code.jquery.com; media-src 'self' data:
      https://*.eea.europa.eu https://*.eionet.europa.eu
      https://cmshare.eea.europa.eu; manifest-src 'self'; report-uri
      https://sentry.eea.europa.eu/api/25/security/?sentry_key=36e966c526304fb38680f19ac1927bb5
  annotations: {}
  livenessProbe:
    httpGet:
      path: /ok
      port: http
    periodSeconds: 20
    timeoutSeconds: 10
    initialDelaySeconds: 30
    failureThreshold: 6
    successThreshold: 1
  startupProbe:
    httpGet:
      path: /ok
      port: http
    periodSeconds: 5
    timeoutSeconds: 10
    initialDelaySeconds: 10
    failureThreshold: 12
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /ok
      port: http
    periodSeconds: 15
    timeoutSeconds: 10
    initialDelaySeconds: 60
    failureThreshold: 4
    successThreshold: 2
  nodeSelector: {}
  tolerations: []
  affinity: {}

varnish:
  serviceType: ClusterIP
  serviceName: frontend-varnish
  image:
    repository: eeacms/plone-varnish
    tag: latest
    pullPolicy: Always
  port: 3000
  backend: frontend-volto
  resources:
    limits:
      memory: 3Gi
    requests:
      memory: 2Gi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  environment:
    VARNISH_SIZE: "2G"
    VARNISH_DNS_TTL: "20s"
    VARNISH_BERESP_TTL: "15s"
    VARNISH_BERESP_GRACE: "100s"
    VARNISH_BERESP_KEEP: "120s"
    VARNISH_GZIP_ENABLED: "true"
    VARNISH_GZIP_JSON_ENABLED: "true"
    VARNISH_CLEAR_OTHER_COOKIES: "true"
    AUTOKILL_CRON: ""
  livenessProbe:
    httpGet:
      path: /ok
      port: http
    periodSeconds: 10
    timeoutSeconds: 10
    initialDelaySeconds: 30
    failureThreshold: 5
    successThreshold: 1
  startupProbe:
    httpGet:
      path: /ok
      port: http
    periodSeconds: 5
    timeoutSeconds: 10
    initialDelaySeconds: 10
    failureThreshold: 12
    successThreshold: 1

nginx:
  serviceType: ClusterIP
  serviceName: frontend-nginx
  image:
    repository: nginx
    tag: "1.23.3"
    pullPolicy: IfNotPresent
  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 512Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

debug:
  addonsPath: /app/src/addons
  affinity: {}
  enabled: false
  environment: {}
  nodeSelector: {}
  podAnnotations: {}
  podSecurityContext: {}
  resources:
    limits:
      memory: 3Gi
    requests:
      memory: 3Gi
  securityContext: {}
  serviceType: ClusterIP
  tolerations: []
