apiVersion: v2
name: goldpinger-rbac
description: "Namespaced Role + RoleBinding granting Goldpinger's ServiceAccount 'pods: list' (peer discovery for node-connectivity-alerter)"
icon: https://raw.githubusercontent.com/eea/helm-charts/main/sources/goldpinger-rbac/kubernetes.png

type: application

keywords:
- Role
- RoleBinding
- ServiceAccount
- goldpinger
- rbac

version: 0.0.1
