apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.role.name }}
  namespace: {{ .Release.Namespace }}
rules:
  {{- range .Values.role.rules }}
  - apiGroups: {{ toJson .apiGroups }}
    resources: {{ toJson .resources }}
    verbs: {{ toJson .verbs }}
  {{- end }}
