goldpinger:
  tolerations:
    - operator: Exists
  rbac:
    create: false
    clusterscoped: true
  serviceAccount:
    create: false
    name: default
  extraEnv:
    - name: HOSTS_TO_RESOLVE
      value: "goldpinger-peers:8080"

  serviceMonitor:
    enabled: true
    interval: 30s
    selector:
      release: kube-prometheus-stack
  prometheusRule:
    enabled: false

monitoring:
  additionalLabels:
    release: kube-prometheus-stack

  prometheusRule:
    enabled: true
    alertName: NodeConnectivityLost
    severity: warning
    for: 3m
    window: 2m
    minPeers: 2
    expr: ""
