#
# Allow the ingress controller to reach the front service exposed by the chart.
#
{{ if .Values.ingress.enabled }}
{{- $frontComponent := include "appl.frontComponent" . -}}
{{- $frontPort := include "appl.frontServicePort" . -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-nginx-ingress
  labels:
    {{- include "appl.labels" . | nindent 4 }}

spec:
  podSelector:
    matchLabels:
      {{- include "appl.selectorLabels" . | nindent 6 }}
      component: {{ $frontComponent }}
  policyTypes:
  - Ingress

  ingress:
  - ports:
    - port: {{ $frontPort }}
      protocol: TCP
{{- end }}
