{{- if .Values.oldIngress.enabled -}}
{{- if and .Values.oldIngress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.oldIngress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.oldIngress.annotations "kubernetes.io/ingress.class" .Values.oldIngress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "appl.fullname" . }}-old-ingress
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: old-eunis-ingress
  annotations:
    {{- with .Values.oldIngress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.oldIngress.restrictFromInternet }}
    nginx.ingress.kubernetes.io/whitelist-source-range: |
      192.168.60.0/22,
      192.168.64.0/21,
      10.92.24.0/21,
      10.50.0.0/16,
      10.20.30.0/24,
      10.0.9.0/24,
      10.50.7.57
    {{- end }}
spec:
  {{- if and .Values.oldIngress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.oldIngress.className }}
  {{- end }}
  rules:
    {{- range .Values.oldIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "appl.tomcatServiceName" $ }}
                port:
                  number: {{ $.Values.service.port }}
              {{- else }}
              serviceName: {{ include "appl.tomcatServiceName" $ }}
              servicePort: {{ $.Values.service.port }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
