{{- if and .Values.ingress.enabled .Values.redirects.enabled }}
{{- $fullName := include "appl.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.redirects.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.redirects.annotations "kubernetes.io/ingress.class" .Values.ingress.className }}
  {{- end }}
{{- end }}
{{- range $ruleIndex, $rule := .Values.redirects.rules }}
{{- if and $rule.path $rule.target }}
---
{{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $.Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ printf "%s-redirect-%d" $fullName $ruleIndex | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "appl.labels" $ | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: {{ $rule.target | quote }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- with $.Values.redirects.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if $.Values.ingress.className }}
  ingressClassName: {{ $.Values.ingress.className }}
  {{- end }}
  {{- if $.Values.ingress.tls }}
  tls:
    {{- range $.Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $.Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ $rule.path }}
            {{- if and $rule.pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ $rule.pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
