apiVersion: v2
name: eionet-plonesaas
description: PloneSaaS configuration for the Eionet portal
icon: https://raw.githubusercontent.com/eea/helm-charts/main/sources/eionet-plonesaas/icon.svg

type: application

keywords:
- Eionet

version: 0.1.0

