apiVersion: v2
appVersion: "9"
description: EEA Elasticsearch 9 cluster to be used with elastic apps
icon: https://raw.githubusercontent.com/eea/helm-charts/main/sources/elastic9/elastic-engine.png

type: application

keywords:
  - Database

name: elastic9
version: 0.1.0
