apiVersion: v1
kind: Secret
metadata:
  name: {{ include "appl.fullname" . }}-instance-env
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    app.kubernetes.io/component: zope
type: Opaque
stringData:
  BEAKER_SECRET: '{{ .Values.instance.env.beakerSecret }}'
  RABBITMQ_PASS: '{{ .Values.instance.env.rabbitmqPass }}'
  SENTRY_DSN: '{{ .Values.instance.env.sentryDSN }}'
