apiVersion: v2
name: bise-frontend
type: application
version: 2.15.2
appVersion: "3.44.0-beta.3"
description: BISE frontend
icon: https://raw.githubusercontent.com/eea/helm-charts/main/sources/bise-frontend/ied.png
home: https://github.com/eea/bise-frontend
keywords:
  - CMS
